const ADD_TODO = 'ADD_TODO'
const DELETE_TODO = 'DELETE_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const CLEAR_TODO = 'CLEAR_TODO'

export {
    ADD_TODO,
    DELETE_TODO,
    TOGGLE_TODO,
    CLEAR_TODO
}